### 变量声明
# @no-log

### 注册
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "username": "admin",
  "email": "admin@example.com",
  "password": "admin12345"
}

### 登录
# @name login
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin12345"
}

> {%
  client.global.set("accessToken", response.body.data.accessToken);
  client.global.set("refreshToken", response.body.data.refreshToken);
%}

### 刷新 Token
POST http://localhost:8080/api/v1/auth/refresh
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

### 登出
POST http://localhost:8080/api/v1/auth/logout
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}
